"""add isin to securities

Revision ID: 7deabfe68488
Revises: adbaaf0a8ab2
Create Date: 2026-08-24 19:39:43.661787

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7deabfe68488"
down_revision: str | Sequence[str] | None = "adbaaf0a8ab2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "securities",
        sa.Column("isin", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    )
    op.drop_index(op.f("ix_securities_ticker"), table_name="securities")
    op.create_unique_constraint("uq_securities_isin", "securities", ["isin"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_securities_isin", "securities", type_="unique")
    op.create_index(
        op.f("ix_securities_ticker"), "securities", ["ticker"], unique=False
    )
    op.drop_column("securities", "isin")
    # ### end Alembic commands ###
