"""add financial statements

Revision ID: 8c7b655c6a0e
Revises: 7deabfe68488
Create Date: 2026-08-25 10:03:43.864222

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c7b655c6a0e"
down_revision: str | Sequence[str] | None = "7deabfe68488"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_filings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "document_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_year", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "document_type",
            "reference_date",
            "version",
            name="uq_financial_filings_identity",
        ),
    )
    op.create_index(
        op.f("ix_financial_filings_company_id"),
        "financial_filings",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "financial_statement_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filing_id", sa.Integer(), nullable=False),
        sa.Column(
            "statement_type",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "exercise_order",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "statement_column",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "account_code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "account_name", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("value", sa.Numeric(precision=30, scale=10), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "currency_scale",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "fixed_account_status",
            sqlmodel.sql.sqltypes.AutoString(length=5),
            nullable=False,
        ),
        sa.Column(
            "source_group", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"],
            ["financial_filings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "filing_id",
            "statement_type",
            "scope",
            "exercise_order",
            "period_start",
            "period_end",
            "statement_column",
            "account_code",
            name="uq_financial_statement_items_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_financial_statement_items_filing_id"),
        "financial_statement_items",
        ["filing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_statement_items_statement_type"),
        "financial_statement_items",
        ["statement_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_financial_statement_items_statement_type"),
        table_name="financial_statement_items",
    )
    op.drop_index(
        op.f("ix_financial_statement_items_filing_id"),
        table_name="financial_statement_items",
    )
    op.drop_table("financial_statement_items")
    op.drop_index(
        op.f("ix_financial_filings_company_id"), table_name="financial_filings"
    )
    op.drop_table("financial_filings")
    # ### end Alembic commands ###
