"""create companies and securities

Revision ID: adbaaf0a8ab2
Revises:
Create Date: 2026-08-24 18:37:59.028700

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adbaaf0a8ab2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cvm_code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("cnpj", sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
        sa.Column(
            "legal_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "trade_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj", name="uq_companies_cnpj"),
        sa.UniqueConstraint("cvm_code", name="uq_companies_cvm_code"),
    )
    op.create_index(op.f("ix_companies_cnpj"), "companies", ["cnpj"], unique=False)
    op.create_index(
        op.f("ix_companies_cvm_code"), "companies", ["cvm_code"], unique=False
    )
    op.create_table(
        "securities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "ticker", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False
        ),
        sa.Column(
            "security_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "security_type IN ('ON', 'PN', 'UNIT', 'OTHER')",
            name="ck_securities_security_type",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", name="uq_securities_ticker"),
    )
    op.create_index(
        op.f("ix_securities_company_id"), "securities", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_securities_ticker"), "securities", ["ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_securities_ticker"), table_name="securities")
    op.drop_index(op.f("ix_securities_company_id"), table_name="securities")
    op.drop_table("securities")
    op.drop_index(op.f("ix_companies_cvm_code"), table_name="companies")
    op.drop_index(op.f("ix_companies_cnpj"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
